### ISSUE TITLE
Where ocamldebug is launched?

### ISSUE THREAD

**Issue by db4** [hackwaly/ocamlearlybird#13]
I've just started to play with this with no success yet (maybe this is due to Windows platform I use). So excuse me for a dumb question: where `ocamldebug` program is launched? I don't see any mention of it in the sources.

**Comment by hackwaly** [comment]
It doesn't use ocamldebug as backend. It use ocaml debug socket as protocol to interact with ocaml vm.

**Comment by db4** [comment]
> It doesn't use ocamldebug as backend. It use ocaml debug socket as protocol to interact with ocaml vm.

I see, you've borrowed some code from `ocamldebug` sources. It's brave decision because you'll have to track `ocamldebug` fixes/changes (if any).

> BTW: Windows and WSL supports are not planed since I have not enough time to work on this project.

That's a pity. [vscode-ocaml](https://github.com/hackwaly/vscode-ocaml) has Windows support, but it's deprecated in favour of this extension that even doesn't plan such support. OK, I could try add it, but if you "have not enough time to work on this project", isn't it going to be deprecated soon as well?

**Comment by hackwaly** [comment]
No, It won't deprecated soon unless there is a mature solution other than ocamlearlybird.

It use this interface https://github.com/ocaml/ocaml/blob/trunk/runtime/caml/debugger.h. It's stable enough.
