### ISSUE TITLE
Support for OCaml 4.07?

### ISSUE THREAD

**Issue by hanjiexi** [hackwaly/ocamlearlybird#2]
I'm currently unable to install ocamlearlybird on my OCaml 4.07 switch since `earlybird.opam` requires `"ocaml" {>= "4.06" & < "4.07"}`. However, I was able to compile it just fine after applying the fix in #1.

And it does appear to launch and connect to VS Code just fine, although I'm not sure how to actually use it yet.

**Comment by hackwaly** [comment]
Fine. Track progress https://github.com/ocaml/opam-repository/pull/12828

**Comment by hanjiexi** [comment]
Thank you!

**Comment by villesau** [comment]
@hackwaly would it be possible to make it to support also 4.05.0? Looks like https://github.com/facebook/flow supports only that.
