### ISSUE TITLE
Support for OCaml 4.10

### ISSUE THREAD

**Issue by leungbk** [hackwaly/ocamlearlybird#24]
It would be nice if `earlybird` worked with Ocaml 4.10.

**Comment by hackwaly** [comment]
duplicated by #23

**Comment by EduardoRFS** [comment]
I have it for 4.11, didn't tested it just made it compile, as I noticed that my requirement is 4.09

> https://github.com/EduardoRFS/ocamlearlybird/tree/fold-values-workaround

**Comment by cdaringe** [comment]
i pulled the above branch and confirms that i builds. the vscode debugger ...not sure what it's up to. i pinned the earlybird from the eduardorfs clone into my switch. still, after configuring to point to by .bc executable, vscode doesn't connect. unsure how to debug vscode's debugger launch startup at this point 🤔 there's no output out of the `OCaml Debug` tab

**Comment by EduardoRFS** [comment]
@cdaringe if you're using opam local switches or you don't have opam by default on your environment, the trick is closing all the vscode window, and then running something like

```shell
cd your-project
eval $(opam env)
code .
```

Then on the vscode terminal you can check if things are working by running your `.bc` and `ocamlearlybird` if both works it should also works

**Comment by hackwaly** [comment]
Don't try. The master branch doesn't work with ocaml >= 4.10. I'm working on support ocaml >= 4.10.

**Comment by hackwaly** [comment]
@leungbk 4.11 support is out. 4.10 is not support now. Do 4.10 must be support?

**Comment by leungbk** [comment]
> @leungbk 4.11 support is out. 4.10 is not support now. Do 4.10 must be support?

It's up to you; I don't feel strongly either way. There's already another issue requesting 4.09 and 4.10 support, so I don't think my issue needs to remain open.

Thanks for enabling 4.11 support!
