### ISSUE TITLE
Upload to https://open-vsx.org/ ?

### ISSUE THREAD

**Issue by atagunov** [hackwaly/ocamlearlybird#29]
Hi, many thanks for your hard work, I've got high hopes :)

To my great convenience fresh versions of both of

- [OCaml Platform](https://open-vsx.org/extension/ocamllabs/ocaml-platform)
- [Haskell](https://open-vsx.org/extension/haskell/haskell) 

are available on https://open-vsx.org/ as well as https://marketplace.visualstudio.com/

Would it be too much to ask to make fresh versions of `hackwaly/ocamlearlybird` more readily available to VSCodium afficionados?

Thx!

**Comment by hackwaly** [comment]
Good idea. Added to todo.

**Comment by sim642** [comment]
It's now recommended to use the https://github.com/ocamllabs/vscode-ocaml-platform/#debugging-ocaml-programs-experimental extension which also seems to be on https://open-vsx.org/extension/ocamllabs/ocaml-platform.
Unfortunately 1.13, which brings the earlybird support, didn't automatically get published there but hopefully it will soon (I pinged someone about it).
