### ISSUE TITLE
Support for OCaml 4.05.0?

### ISSUE THREAD

**Issue by villesau** [hackwaly/ocamlearlybird#3]
Looks like [Flow](https://github.com/facebook/flow) only supports OCaml 4.05.0 but this plugin is for 4.06.0 and 4.07.0. Would it be posible to change earlybird to support 4.05.0 version too? Is there anything preventing from that? Regarding my tests Flow does not compile using later versions than 4.05.0.

**Comment by villesau** [comment]
Looks like Flow compiles with 4.06.0 after all, I just had some crap in build forlder.

**Comment by hackwaly** [comment]
There may be some code need 4.06 I think. Anyway, support 4.05 isn't much difficult. I'll work on it.

**Comment by hackwaly** [comment]
Track progress: https://github.com/ocaml/opam-repository/pull/12839
