### ISSUE TITLE
... make sure ocamlearlybird in your PATH.

### ISSUE THREAD

**Issue by PavelKotov1** [hackwaly/ocamlearlybird#37]
Hello, dear friends!
I apologize in advance for such a silly question, but i am comming from windows world and simply do not know linux well enough:
Question: how to add ocamlearlybird in my PATH?
Do i add  the executable files themselves OR symlinks to the executable?
And what are the names of executable of ocamlearlybird? What exactly do i "export"?
I did "locate earlybird" and it gave my pages of names...
If possible be very specific, please.
Thanks in advance!

**Comment by hackwaly** [comment]
If you are using window. I recommend you to use WSL2 to get linux env.

**Comment by PavelKotov1** [comment]
no, i am not using windows, i am using ubuntu 20.04.
 So my question is how to add ocamlearlybird to PATH on ubuntu?

**Comment by hackwaly** [comment]
You just need to setup opam properly. Then use opam to install earlybird.

**Comment by PavelKotov1** [comment]
ok, one more question, hope you do not mind:
When i follow your example https://imgur.com/U3GDHXM, everything works fine: 
I click on test_program.bc, select "Start an Ocaml debug session", and the execution goes into the stdlib.ml. 
How do i put a breakpoint into the test_program.ml and step through its the source code? Because i would like to learn ocaml source code debugging.
Thanks in advance!

**Comment by hackwaly** [comment]
Just look at the loaded modules in vscode's debug pannel. You can set breakpoints in those files there.

**Comment by PavelKotov1** [comment]
Well, that's the problem: i set up the breakpoints test_program.ml,  but they are never hit.
How do i direct execution into test_program.ml file? If i open it separately, it just sits there and the execution keeps running in the libraries...

**Comment by hackwaly** [comment]
Press "run"

**Comment by PavelKotov1** [comment]
ok, sorry for the delay! I finally figure it out and everything works now!
There are so many pieces to this puzzle and even the smallest one breaks it if you get it wrong. My problem was launch.json file, which was need to be set correctly.
So, thans again for the great tool, guys! 
RESPECT!
