### ISSUE TITLE
opam can't find earlybird on opam 1.2.2 and ocaml 4.02.3 on WSL

### ISSUE THREAD

**Issue by Jonas164** [hackwaly/ocamlearlybird#4]
I am trying to setup my Ocaml dev environment on Windows with WSL. Sadly, opam can't find the earlybird package, even after running opam update.

**Comment by hackwaly** [comment]
Use opam 2.0 if possible. The minimal ocaml version supported is 4.04

**Comment by Jonas164** [comment]
Opam 2.0 does not seem to be available for WSL sadly.

**Comment by hackwaly** [comment]
What about OCaml 4.04 ~ 4.07. I don't know if they are supported on WSL. Opam version should not care

**Comment by Jonas164** [comment]
Tried it on ocaml 4.04. Still not working
![image](https://user-images.githubusercontent.com/29672890/48838293-38423b80-ed88-11e8-8953-1054fde84f20.png)

**Comment by hackwaly** [comment]
https://opam.ocaml.org/doc/Upgrade_guide.html#What-you-need-to-be-aware-of_1
According to these statements. 1.2 repo no longer accepts new package to publish on it. This issue should can not be solved.
