### ISSUE TITLE
Modules in byte code executable file build by dune are not found when adding fragment in Controller.root function.

### ISSUE THREAD

**Issue by Mng12345** [hackwaly/ocamlearlybird#57]
I have noticed that we can not set breakpoints in vscode for dune build bc executable file, and i build a custom earlybird with printting some logs in the console, the logs show that some modules are not found when adding fragment.
![image](https://github.com/hackwaly/ocamlearlybird/assets/21278900/da97be8d-d9c0-4783-8551-61966e0e8f11)
Below are some parts of the console log.
```
resolve module source for: Printast is not found.
resolve module source for: Dune__exe__CompletionFrontEnd is not found.
resolve module source for: Parse is not found.
resolve module source for: Res_driver is not found.
resolve module source for: Res_driver_ml_parser is not found.
resolve module source for: Res_ast_debugger is not found.
resolve module: 
source path: /home/ming/.opam/4.14.0/lib/ocaml/camlinternalFormat.ml
content: (*****************************

resolve module source for: Dune__exe__Files is not found.
resolve module source for: Reanalyze__DeadModules is not found.
resolve module source for: Dune__exe__ProcessCmt is not found.
resolve module source for: Ext_pervasives is not found.
resolve module source for: Dune__exe__ResolvePath is not found.
resolve module source for: Res_outcome_printer is not found.
resolve module: 
source path: /home/ming/.opam/4.14.0/lib/ocaml/list.ml
content: (*****************************

resolve module source for: Unix is not found.
resolve module source for: Asttypes is not found.
resolve module: 
source path: /home/ming/.opam/4.14.0/lib/ocaml/camlinternalAtomic.ml
content: (*****************************

resolve module source for: Res_printer is not found.
resolve module source for: Dune__exe__SignatureHelp is not found.
resolve module: 
source path: /home/ming/.opam/4.14.0/lib/ocaml/marshal.ml
content: (*****************************
```

**Comment by Mng12345** [comment]
> Have you noticed https://github.com/hackwaly/ocamlearlybird?tab=readme-ov-file#breakpoints-not-hit-with-lang-dune-30-and-above

Thanks for the reply, i have already changed my dune version to 3.7 and set `(map_workspace_root false)`, the breakpoints are still unrerified.

**Comment by hackwaly** [comment]
You could set `source_dirs` in launch.json to specify additional search dirs. See https://github.com/hackwaly/ocamlearlybird/blob/63f0a3fbc2fc0af388f984da1d447eefa708c39b/src/adapter/debug_protocol_ex.ml#L46

**Comment by Mng12345** [comment]
Yes, this still not fix my problem.

**Comment by Mng12345** [comment]
And i noticed that the module name has be changed in the debuginfo of bc executable file. Eg, the source file is Cli.ml, but it changed to Dune__exe__Cli, did this changes will break the module resolving? I am not very familar with ocamlearlybird code.
![image](https://github.com/hackwaly/ocamlearlybird/assets/21278900/3e82edf3-730a-48e9-9fdf-43a468af12b0)

**Comment by hackwaly** [comment]
I think it won't. You can log the `search_dirs` and dig into search_dirs to see what's inside. Maybe this will give us some clues.

**Comment by hackwaly** [comment]
It seems your (map_workspace_root false) not takes effect.

**Comment by Mng12345** [comment]
Ohh! sorry, it's my fault, i forgot to change map_workspace_root true to false!! It works now, thank!
![image](https://github.com/hackwaly/ocamlearlybird/assets/21278900/c2f6a8fd-d7d5-40e7-a983-8a4108b2d887)
