### ISSUE TITLE
Does Earlybird support breaking in dynamically loaded code?

### ISSUE THREAD

**Issue by jacj-simcorp** [hackwaly/ocamlearlybird#64]
Hi, I have issues getting my breakpoints to be hit in code loaded via `Dynlink` at runtime.

Before I investigate this further I would like to ask if this is even supported? 

Thanks.

**Comment by hackwaly** [comment]
Yes, it supposed to be supported. There's related code https://github.com/hackwaly/ocamlearlybird/blob/0a7bee00ee73683493934771ab38200d13fa0e7f/src/debugger/core/wire_protocol.ml#L62.

**Comment by jacj-simcorp** [comment]
Thanks, then I will pursue this further.

**Comment by hackwaly** [comment]
> Thanks, then I will pursue this further.

I didn't tested this. So it may not function at all.
