### ISSUE TITLE
How to pass command line arguments to a debugee?

### ISSUE THREAD

**Issue by RyanGibb** [hackwaly/ocamlearlybird#75]
Ruby's redapt has `programArgs` (https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#with-redapt), vscode-js-debug has `runtimeArgs` (https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#vscode-js-debug-1), and kotlin-debug adapter has `args` (https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#kotlin). I can't seem to find any documentation on if earlybird has a mechanism to pass command line arguments to a program. `args` doesn't seem to do anything.

**Comment by sim642** [comment]
I think `arguments` should work but this probably should be documented somewhere. The example doesn't use this.

**Comment by RyanGibb** [comment]
Ah, that works! Thanks @sim642.

**Comment by sim642** [comment]
I also added this information to README now.
