### ISSUE TITLE
<abstr> type could be perhaps described more accurately

### ISSUE THREAD

**Issue by villesau** [hackwaly/ocamlearlybird#9]
Looks like `<abstr>` is used when type information is hard to retrieve. looks like `path` has some more info about the `<abstr>` type. e.g in this case `cx` has type `Context` when attaching debugger on line https://github.com/hackwaly/ocamlearlybird/blob/master/ocaml_debug_adapter/inspect.ml#L367

There might be even more information that could be shown in debugger. I think that `cx` in this case has some data in it too, but only `<abstr>` is shown. this is how cx looks like: https://github.com/facebook/flow/blob/master/src/typing/context.ml

<img width="233" alt="screenshot 2018-12-20 at 0 44 55" src="https://user-images.githubusercontent.com/2647016/50252775-b9750880-03f0-11e9-955b-a4ab8c1b8e3e.png">

**Comment by villesau** [comment]
I think that in this case the `<abstr>` `cx` type is actually [_record_](https://v1.realworldocaml.org/v1/en/html/records.html).

**Comment by villesau** [comment]
@hackwaly unfortunately I don't have simpler code base for you :/ But I _think_ that it actually happens with ocamlearlybird as well but i'm not 100% sure.

Here are debugging instructions for Flow: https://github.com/facebook/flow/issues/4181#issuecomment-447596374

If you put breakpoint in `flow_js.ml` to any place that uses `cx` variable, you see the problem.

**Comment by hackwaly** [comment]
superseded by https://github.com/hackwaly/ocamlearlybird/issues/52
